name: Twist
main: ru.ostrov77.twist.Main
version: 2.0
api-version: 1.16
author: komiss77
depend: [Ostrov]
softdepend: [NoteBlockAPI]
load: POSTWORLD
commands:
   tw:
      description: Main command
   twist:
      description: Main command
