name: Twist
main: ru.ostrov77.twist.Twist
version: 2.0
api-version: 1.16
author: komiss77
depend: [Ostrov, MiniGames]
softdepend: [NoteBlockAPI]
load: POSTWORLD
commands:
   twist:
      description: Main command
      usage: /twist [action]
      aliases: [tw]